# Generated by Django 3.0.2 on 2020-02-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200212_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Subject',
            field=models.CharField(default='', max_length=400),
        ),
    ]
