# Generated by Django 3.0.2 on 2020-04-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
