# Generated by Django 3.0.2 on 2020-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(default='', upload_to='hello\\static\\ktk\\images'),
        ),
    ]
