# Generated by Django 3.0.2 on 2020-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20200405_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(default='', upload_to='hello\\static\\ktk\\images\\quotes'),
        ),
    ]
