# Generated by Django 3.0.2 on 2020-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20200405_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
