# Generated by Django 3.0.2 on 2020-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20200406_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(default='', upload_to='review_photo'),
        ),
    ]
