# Generated by Django 3.0.2 on 2020-06-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(default='review_photo/default.png', upload_to='review_photo'),
        ),
    ]
